// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/webhooks/customers/data_request": {
    params: {};
  };
  "/webhooks/app/scopes_update": {
    params: {};
  };
  "/webhooks/customers/redact": {
    params: {};
  };
  "/webhooks/app/uninstalled": {
    params: {};
  };
  "/webhooks/shop/redact": {
    params: {};
  };
  "/api/trackers/delete": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/auth/*": {
    params: {
      "*": string;
    };
  };
  "/app": {
    params: {};
  };
  "/app/trackers/:id": {
    params: {
      "id": string;
    };
  };
  "/app/trackers/new": {
    params: {};
  };
  "/app/additional": {
    params: {};
  };
  "/app/billing": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/webhooks/customers/data_request" | "/webhooks/app/scopes_update" | "/webhooks/customers/redact" | "/webhooks/app/uninstalled" | "/webhooks/shop/redact" | "/api/trackers/delete" | "/auth/login" | "/auth/*" | "/app" | "/app/trackers/:id" | "/app/trackers/new" | "/app/additional" | "/app/billing";
  };
  "routes/webhooks.customers.data_request.jsx": {
    id: "routes/webhooks.customers.data_request";
    page: "/webhooks/customers/data_request";
  };
  "routes/webhooks.app.scopes_update.jsx": {
    id: "routes/webhooks.app.scopes_update";
    page: "/webhooks/app/scopes_update";
  };
  "routes/webhooks.customers.redact.jsx": {
    id: "routes/webhooks.customers.redact";
    page: "/webhooks/customers/redact";
  };
  "routes/webhooks.app.uninstalled.jsx": {
    id: "routes/webhooks.app.uninstalled";
    page: "/webhooks/app/uninstalled";
  };
  "routes/webhooks.shop.redact.jsx": {
    id: "routes/webhooks.shop.redact";
    page: "/webhooks/shop/redact";
  };
  "routes/api.trackers.delete.jsx": {
    id: "routes/api.trackers.delete";
    page: "/api/trackers/delete";
  };
  "routes/auth.login/route.jsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/_index/route.jsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/auth.$.jsx": {
    id: "routes/auth.$";
    page: "/auth/*";
  };
  "routes/app.jsx": {
    id: "routes/app";
    page: "/app" | "/app/trackers/:id" | "/app/trackers/new" | "/app/additional" | "/app/billing";
  };
  "routes/app.trackers.$id.jsx": {
    id: "routes/app.trackers.$id";
    page: "/app/trackers/:id";
  };
  "routes/app.trackers.new.jsx": {
    id: "routes/app.trackers.new";
    page: "/app/trackers/new";
  };
  "routes/app.additional.jsx": {
    id: "routes/app.additional";
    page: "/app/additional";
  };
  "routes/app.billing.jsx": {
    id: "routes/app.billing";
    page: "/app/billing";
  };
  "routes/app._index.jsx": {
    id: "routes/app._index";
    page: "/app";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/webhooks.customers.data_request": typeof import("./app/routes/webhooks.customers.data_request.jsx");
  "routes/webhooks.app.scopes_update": typeof import("./app/routes/webhooks.app.scopes_update.jsx");
  "routes/webhooks.customers.redact": typeof import("./app/routes/webhooks.customers.redact.jsx");
  "routes/webhooks.app.uninstalled": typeof import("./app/routes/webhooks.app.uninstalled.jsx");
  "routes/webhooks.shop.redact": typeof import("./app/routes/webhooks.shop.redact.jsx");
  "routes/api.trackers.delete": typeof import("./app/routes/api.trackers.delete.jsx");
  "routes/auth.login": typeof import("./app/routes/auth.login/route.jsx");
  "routes/_index": typeof import("./app/routes/_index/route.jsx");
  "routes/auth.$": typeof import("./app/routes/auth.$.jsx");
  "routes/app": typeof import("./app/routes/app.jsx");
  "routes/app.trackers.$id": typeof import("./app/routes/app.trackers.$id.jsx");
  "routes/app.trackers.new": typeof import("./app/routes/app.trackers.new.jsx");
  "routes/app.additional": typeof import("./app/routes/app.additional.jsx");
  "routes/app.billing": typeof import("./app/routes/app.billing.jsx");
  "routes/app._index": typeof import("./app/routes/app._index.jsx");
};